# Configuration of the CI pipeline
name: 'Amazon requirements'
canonical: 'aws-requirements'
description: 'Create optionnaly an S3 bucket for terraform, IAM user as admin and codecommit repository.'
keywords:
  - 's3'
  - 'iam'
  - 'codecommit'
  - 'aws'
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/infra-amazon-req/master/icon.png'
type: 'infra'
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/req.yml'
    variables:
      path: 'pipeline/variables.yml.sample'

  # Configuration of ansible for provisionning
  ansible: {}

  # Configuration of terraform to setup the infrastructure
  terraform:
    req:
      path: 'terraform/req.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/req.tf'
